import type { Metadata } from "next";
import { Manrope } from "next/font/google";
// import { sahel } from "@/next-persian-fonts/sahel";
// import { ray, rayBold } from "@/next-persian-fonts/ray";
import "./globals.css";
import Navbar from "@/components/global/navbar";
import Footer from "@/components/global/footer";

const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable}  antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
